#!/bin/bash

export SOCIAL_AUTH_VK_APP_KEY=
export SOCIAL_AUTH_VK_APP_SECRET=

export SOCIAL_AUTH_VK_OAUTH2_KEY=
export SOCIAL_AUTH_VK_OAUTH2_SECRET=

export SOCIAL_AUTH_FACEBOOK_KEY=
export SOCIAL_AUTH_FACEBOOK_SECRET=

export TMDB_KEY=
export OMDB_KEY=

export EMAIL_HOST_PASSWORD=
