[tox]
envlist = py-{pytest,mypy,ruff,rstlint}
skipsdist = True
isolated_build = true

[testenv]
basepython = python3.11
setenv =
    PYTHONPATH = src
sitepackages = false
envdir =
    py-pytest: {toxworkdir}/py-pytest
    py-rstlint: {toxworkdir}/py-rstlint
    py-mypy: {toxworkdir}/py-mypy
    py-ruff: {toxworkdir}/py-ruff
allowlist_externals =
    make
    echo
    uv

commands_pre =
    uv sync --active

commands =
    requirements: echo "Install requirements"
    bandit: bandit -r src --exclude src/{env:APP}/tests
    #safety: safety check
    pytest: py.test src
    rstlint: rst-lint README.rst doc.rst
    mypy: mypy src --explicit-package-bases
    ruff: ruff check src
