# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 00:53

import annoying.fields
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moviesapp", "0012_auto_20170423_1807"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailers_en",
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailers_ru",
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
