# Generated by Django 2.0.2 on 2018-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0016_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="watched_extended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="watched_in_theatre",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="watched_original",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский")], default="en", max_length=2, verbose_name="Language"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="user",
            name="only_for_friends",
            field=models.BooleanField(
                default=False, help_text="Show my lists only to friends", verbose_name="Privacy"
            ),
        ),
    ]
