# Generated by Django 2.2.19 on 2021-04-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0019_auto_20180329_0318"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="learned_words",
        ),
    ]
