# Generated by Django 3.2 on 2021-04-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0021_alter_user_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
    ]
