# Generated by Django 4.0.4 on 2022-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0022_remove_user_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="trailers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailers_en",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailers_ru",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
