# Generated by Django 4.0.4 on 2022-05-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0023_alter_movie_trailers_alter_movie_trailers_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionrecord",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
