# Generated by Django 4.0.4 on 2022-05-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0024_alter_actionrecord_rating_alter_movie_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='key_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
