# Generated by Django 4.0.5 on 2022-06-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0029_providerrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_data_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
