# Generated by Django 4.0.5 on 2022-06-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0031_alter_action_name_alter_action_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description_en',
            new_name='overview_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description_ru',
            new_name='overview_ru',
        ),
    ]
