# Generated by Django 4.0.5 on 2022-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0032_rename_description_movie_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
