# Generated by Django 4.0.5 on 2022-06-26 05:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0033_record_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkCountry',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='Country')),
            ],
        ),
    ]
