# Generated by Django 4.0.5 on 2022-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0035_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Don't show my lists to anybody", verbose_name='Hide account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='only_for_friends',
            field=models.BooleanField(default=False, help_text='Show my lists only to friends', verbose_name='Only for friends'),
        ),
    ]
