# Generated by Django 4.2.23 on 2025-08-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0037_alter_vkcountry_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="action",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="list",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="list",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="overview_en",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="overview_ru",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="poster_en",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="poster_ru",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="trailers_en",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="trailers_ru",
        ),
    ]
