# Generated by Django 5.2.4 on 2025-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0038_remove_action_name_en_remove_action_name_ru_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VkCountry",
        ),
        migrations.AddField(
            model_name="record",
            name="ignore_rewatch",
            field=models.BooleanField(default=False),
        ),
    ]
