# Generated by Django 5.2.4 on 2025-08-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0040_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_big",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_small",
        ),
    ]
