# Generated by Django 5.2.4 on 2026-03-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0042_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
