name: CI/CD
on: push

jobs:
  ci_cd:
    name: Run CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org
      - name: Install test requirements
        run: |
          rm package.json
          npm install eslint@7.22.0
          npm install csscomb-linter@0.0.4
          npm install eslint-config-google@0.14.0
          npm install eslint-plugin-vue@7.7.0
          npm install jsonlint@1.6.3
          pip install tox
          tox -e py37-requirements
      - name: Run tests
        run: make test
      - name: Install codecov requirements
        run: pip install coverage
      - name: Run codecov
        uses: codecov/codecov-action@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.actor }}/movies/movies
          tags: latest
