---
name: Remove Unused Movies
on:
  schedule:
    - cron: "0 7 1 * *"  # Runs at 07:00 UTC (03:00 EDT) on the first day of the month
  workflow_dispatch:

jobs:
  remove_unused_movies:
    name: Remove unused movies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.1

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo $KUBECONFIG > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Done as a variable because it doesn't work in place.

      - name: Remove unused movies
        run: make prod-manage remove_unused_movies
