---
name: Restart App
on:
  workflow_dispatch:
jobs:
  restart_app:
    name: Restart app
    uses: ./.github/workflows/reusable_restart_app.yaml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    secrets: inherit
