---
name: Restart App
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  restart_app:
    name: Restart app
    uses: ./.github/workflows/reusable_restart_app.yaml
    secrets: inherit
