---
name: Update Movie Data Starting From Movie ID
on:
  workflow_dispatch:
    inputs:
      movie_id:
        description: "Movie ID"
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  update_movie_data:
    name: Update movie data starting from movie ID
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.0

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: "1.135.0"

      - name: Update all movies starting from selected movie ID
        run: make prod-manage update_movie_data arguments="-s ${{ github.event.inputs.movie_id }}"
